name: eods-f21
channels: 
    - conda-forge
dependencies:
    - python=3.8.*
    - pandas=1.3.*
    - scikit-learn=0.24.*
    - ipython
    - ipykernel
    - ipywidgets
    - statsmodels
    - seaborn
    - spacy
    - nltk
    - beautifulsoup4
    - pandas-datareader
    - xlrd
    - openpyxl
    - twython
    - sqlalchemy
    - pandasql
    - pymongo
    - nbformat
    - plotly
    - pillow
    - pyarrow
    - flask
    - mlxtend
    - imbalanced-learn
